[project]
name = "deepsort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deep-sort-realtime>=1.3.2",
    "opencv-python>=4.11.0.86",
    "setuptools>=78.1.0",
    "ultralytics>=8.3.107",
]
